server:
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.161.255:3307/LOL?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200
  #redis相关配置
  redis:
    host: 47.98.161.255
    password: password
    port: 6380
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 20
        min-idle: 2